# -*- coding: utf-8 -*-
"""Canonical slug map for the 69 Keyword Planner phrases."""
from pathlib import Path

KEYWORDS = [
    (1, "استرجاع حساب انستقرام", "istirja-hisab-instagram", "استرجاع"),
    (2, "استرجاع حساب الانستا", "istirja-hisab-alinsta", "استرجاع"),
    (3, "فتح حسابي انستقرام", "fath-hisabi-instagram", "استرجاع"),
    (4, "رابط استرجاع حساب انستقرام", "rabit-istirja-hisab-instagram", "روابط"),
    (5, "اختراق حساب الانستقرام", "ikhtiraq-hisab-alinstagram", "اختراق"),
    (6, "استرجاع حساب الانستقرام المعطل", "istirja-hisab-alinstagram-almuattal", "معطل"),
    (7, "استرجاع حساب انستقرام عن طريق اسم المستخدم", "istirja-bi-ism-almustakhdam-kw", "دخول"),
    (8, "استرجاع حساب انستقرام عن طريق الدعم الفني", "istirja-via-daam-fanni", "دعم"),
    (9, "استرجاع حساب انستقرام من قوقل", "istirja-min-google-kw", "دخول"),
    (10, "استرجاع حسابي", "istirja-hisabi", "استرجاع"),
    (11, "استرداد حساب الانستا", "istirdad-hisab-alinsta", "استرجاع"),
    (12, "استرداد حسابي انستا", "istirdad-hisabi-insta", "استرجاع"),
    (13, "استعادة حساب الانستقرام", "istiada-hisab-alinstagram", "استرجاع"),
    (14, "تم اختراق حسابي انستقرام", "tam-ikhtiraq-hisabi-instagram", "اختراق"),
    (15, "تم الغاء تنشيط حسابي على الانستغرام", "tam-ilgha-tansheet-hisabi", "معطل"),
    (16, "حسابي الانستا", "hisabi-alinsta", "استرجاع"),
    (17, "رابط استرجاع حساب انستقرام معطل", "rabit-istirja-muattal", "روابط"),
    (18, "صورة حساب مبند", "surat-hisab-mubannad", "حظر"),
    (19, "نسيت كلمة السر للانستقرام", "naseet-kalimat-sirr-lilinstagram", "كلمة سر"),
    (20, "إرجاع حساب انستا", "irja-hisab-insta", "استرجاع"),
    (21, "إسترجاع انستقرام", "istirjaa-instagram", "استرجاع"),
    (22, "استرجاع الانستا المعطل", "istirja-alinsta-almuattal", "معطل"),
    (23, "استرجاع حساب الانستقرام المحذوف", "istirja-alinstagram-almahdhuf", "محذوف"),
    (24, "استرجاع حساب الانستقرام عن طريق رقم الهاتف", "istirja-bi-raqm-alhatif", "دخول"),
    (25, "استرجاع حساب انستا مبند", "istirja-insta-mubannad", "حظر"),
    (26, "استرجاع حساب انستا محذوف", "istirja-insta-mahdhuf", "محذوف"),
    (27, "استرجاع حساب انستقرام عن طريق الايميل", "istirja-bi-alemail", "دخول"),
    (28, "استرجاع حساب انستقرام عند فقدان الايميل رقم الهاتف كلمة السر", "istirja-bidun-email-raqm-sirr", "دخول"),
    (29, "استرجاع حساب انستقرام محذوف نهائي", "istirja-mahdhuf-nihai", "محذوف"),
    (30, "استرجاع حساب انستقرام مخترق", "istirja-mukhtaraq-kw", "اختراق"),
    (31, "استرجاع حساب انستقرام معطل نهائيا", "istirja-muattal-nihaiyan", "معطل"),
    (32, "استرجاع حساب معطل انستقرام", "istirja-hisab-muattal-instagram", "معطل"),
    (33, "استرجاع حسابي الانستا", "istirja-hisabi-alinsta", "استرجاع"),
    (34, "استرجاع حسابي انستا", "istirja-hisabi-insta", "استرجاع"),
    (35, "استرجاع كلمة السر انستقرام", "istirja-kalimat-sirr-instagram", "كلمة سر"),
    (36, "استرداد حساب انستقرام معطل", "istirdad-hisab-instagram-muattal", "معطل"),
    (37, "استعادة حساب الانستقرام المعطل", "istiada-hisab-alinstagram-almuattal", "معطل"),
    (38, "استعادة كلمة مرور انستقرام برقم الجوال", "istiada-kalimat-murur-bi-jawwal", "كلمة سر"),
    (39, "استعاده حساب انستا", "istiada-hisab-insta", "استرجاع"),
    (40, "استعاده حسابي", "istiada-hisabi", "استرجاع"),
    (41, "اعادة تعيين كلمة سر انستقرام", "iadat-tayin-kalimat-sirr", "كلمة سر"),
    (42, "اعادة تعيين كلمة مرور انستقرام", "iadat-tayin-kalimat-murur", "كلمة سر"),
    (43, "اعادة تنشيط حساب انستا", "iadat-tansheet-hisab-insta", "معطل"),
    (44, "اغلاق حساب انستقرام مؤقتا", "ighlaq-hisab-instagram-muaqqatan", "إغلاق"),
    (45, "البحث عن حسابي انستقرام", "albahth-an-hisabi-instagram", "دخول"),
    (46, "الغاء تنشيط حساب انستقرام", "ilgha-tansheet-hisab-instagram", "إغلاق"),
    (47, "ترجيع حساب انستا", "tarji-hisab-insta", "استرجاع"),
    (48, "حساب الانستقرام معطل", "hisab-alinstagram-muattal", "معطل"),
    (49, "حساب انستا مبند", "hisab-insta-mubannad", "حظر"),
    (50, "حسابى على انستجرام", "hisabi-ala-instajram", "استرجاع"),
    (51, "حسابي الانستا معطل", "hisabi-alinsta-muattal", "معطل"),
    (52, "دخول الى حساب انستقرام", "dukhul-ila-hisab-instagram", "دخول"),
    (53, "رابط استرجاع حساب انستقرام مبند", "rabit-istirja-mubannad", "روابط"),
    (54, "رابط استرجاع حساب انستقرام محذوف", "rabit-istirja-mahdhuf", "روابط"),
    (55, "رابط تعطيل حساب الانستقرام مؤقت", "rabit-taattil-muaqqat", "إغلاق"),
    (56, "طريقة استرجاع حساب الانستقرام", "tariqat-istirja-hisab-alinstagram", "استرجاع"),
    (57, "طريقة تعطيل حساب انستا", "tariqat-taattil-hisab-insta", "إغلاق"),
    (58, "عطل الانستقرام", "atal-alinstagram", "معطل"),
    (59, "غلق حساب انستا", "ghalq-hisab-insta", "إغلاق"),
    (60, "كيفية استرجاع الانستقرام", "kayfiyat-istirja-alinstagram", "استرجاع"),
    (61, "كيفية استرجاع حساب الانستقرام", "kayfiyat-istirja-hisab-alinstagram", "استرجاع"),
    (62, "كيفية استرجاع حساب انستقرام محذوف", "kayfiyat-istirja-mahdhuf", "محذوف"),
    (63, "كيفية استرجاع كلمة سر انستقرام", "kayfiyat-istirja-kalimat-sirr", "كلمة سر"),
    (64, "كيفية استعادة حساب الانستقرام", "kayfiyat-istiada-hisab-alinstagram", "استرجاع"),
    (65, "كيفية اغلاق حساب انستقرام", "kayfiyat-ighlaq-hisab-instagram", "إغلاق"),
    (66, "كيفية فتح حساب انستقرام", "kayfiyat-fath-hisab-instagram", "دخول"),
    (67, "مركز المساعدة انستقرام تم تعطيل حسابي", "markaz-almusaada-tam-taattil", "معطل"),
    (68, "نسيت كلمة السر انستقرام والايميل", "naseet-sirr-wa-email", "كلمة سر"),
    (69, "نشر حسابي انستقرام", "nashr-hisabi-instagram", "نشر"),
]

CATEGORY = {
    "استرجاع": "استرجاع الحساب",
    "معطل": "حالات الحساب",
    "اختراق": "الاختراق والأمان",
    "دخول": "الدخول والتحقّق",
    "كلمة سر": "الدخول والتحقّق",
    "محذوف": "حالات الحساب",
    "حظر": "حالات الحساب",
    "روابط": "الاستئناف والدعم",
    "دعم": "الاستئناف والدعم",
    "إغلاق": "حالات الحساب",
    "نشر": "حالات الحساب",
}

if __name__ == "__main__":
    out = Path(__file__).resolve().parents[1] / "docs" / "keywords" / "planner-69-slug-map.md"
    lines = ["# خريطة الـ69 كلمة → slug", ""]
    for n, kw, slug, cluster in KEYWORDS:
        lines.append(f"| {n} | {kw} | `{slug}` | {cluster} | {CATEGORY[cluster]} |")
    out.write_text("\n".join(lines), encoding="utf-8")
    print(len(KEYWORDS), out)
